name: Scraping Cron Job

on:
  schedule:
    # This will run the cron job daily at midnight UTC
    - cron: '*/5 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run the scraping task
        run: |
          curl -X POST https://shared-costing.onrender.com/api/players/create \
          -H "Authorization: Bearer ${{ secrets.SCRAPER_SECRET }}"
